package ca.mcgill.sel.restified.zoorestified;

import eu.kartoffelquadrat.zoo.Animal;
import eu.kartoffelquadrat.zoo.Zoo;
import java.util.Collection;
import eu.kartoffelquadrat.zoo.OpeningHours;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.CrossOrigin;
// Start of user code for imports
// End of user code

/**
 * ZooController class definition.
 * Generated by the TouchCORE code generator.
 */
@RestController 
@CrossOrigin
public class ZooController {
    
    @GetMapping(path="/zoo/openinghours")
    public OpeningHours getOpeningHours() {
        Zoo instance = Zoo.getInstance();
        OpeningHours openingHours = instance.getOpeningHours();
        return openingHours;
    }

    @GetMapping(path="/zoo/animals")
    public Collection getAllAnimalNames() {
        Zoo instance = Zoo.getInstance();
        Collection<String> allAnimalNames = instance.getAllAnimalNames();
        return allAnimalNames;
    }

    @GetMapping(path="/zoo/animals/{animalname}")
    public Animal getAnimalDetails(@PathVariable("animalname") String name) {
        Zoo instance = Zoo.getInstance();
        Animal animalDetails = instance.getAnimalDetails(name);
        return animalDetails;
    }

    @PutMapping(path="/zoo/animals/{animalname}")
    public void addAnimal(@PathVariable("animalname") String name, @RequestBody Animal animal) {
        Zoo instance = Zoo.getInstance();
        instance.addAnimal(name, animal);
    }

    @GetMapping(path="/zoo")
    public static Zoo getInstance() {
        Zoo instance = Zoo.getInstance();
        Zoo instance1 = Zoo.getInstance();
        return instance1;
    }
}
